# Generated by Django 6.0.3 on 2026-03-19 16:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Назва (укр)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Назва (рос)')),
                ('short_desc_uk', models.TextField(max_length=300, verbose_name='Короткий опис (укр)')),
                ('short_desc_ru', models.TextField(max_length=300, verbose_name='Короткий опис (рос)')),
                ('full_desc_uk', models.TextField(verbose_name='Повний опис (укр)')),
                ('full_desc_ru', models.TextField(verbose_name='Повний опис (рос)')),
                ('icon_svg', models.TextField(blank=True, help_text='Вставте SVG-код іконки', verbose_name='SVG-іконка')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Зображення')),
                ('image_alt_uk', models.CharField(blank=True, max_length=200, verbose_name='Alt зображення (укр)')),
                ('image_alt_ru', models.CharField(blank=True, max_length=200, verbose_name='Alt зображення (рос)')),
                ('price_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ціна від (грн)')),
                ('price_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ціна до (грн)')),
                ('price_note_uk', models.CharField(blank=True, max_length=200, verbose_name='Примітка до ціни (укр)')),
                ('price_note_ru', models.CharField(blank=True, max_length=200, verbose_name='Примітка до ціни (рос)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Виділена на головній')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
    ]
