# Generated by Django 6.0.3 on 2026-03-19 16:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_uk', models.CharField(default='Про нас', max_length=300, verbose_name='Заголовок (укр)')),
                ('heading_ru', models.CharField(default='О нас', max_length=300, verbose_name='Заголовок (рос)')),
                ('text_uk', models.TextField(default='Ми — команда досвідчених фахівців з прочищення каналізації у Дніпрі. Працюємо з 2019 року, виконали понад 1000 успішних виїздів. Використовуємо найсучасніше обладнання: електромеханічний апарат ROTHENBERGER R 750, гідродинамічні машини та ілосос з власним Ecoflo.', verbose_name='Текст (укр)')),
                ('text_ru', models.TextField(default='Мы — команда опытных специалистов по прочистке канализации в Днепре. Работаем с 2019 года, выполнили более 1000 успешных выездов. Используем современное оборудование: электромеханический аппарат ROTHENBERGER R 750, гидродинамические машины и илосос с собственным Ecoflo.', verbose_name='Текст (рос)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото команди')),
                ('image_alt_uk', models.CharField(blank=True, max_length=200, verbose_name='Alt фото (укр)')),
                ('image_alt_ru', models.CharField(blank=True, max_length=200, verbose_name='Alt фото (рос)')),
            ],
            options={
                'verbose_name': 'Секція «Про нас»',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uk', models.CharField(max_length=500, verbose_name='Питання (укр)')),
                ('question_ru', models.CharField(max_length=500, verbose_name='Питання (рос)')),
                ('answer_uk', models.TextField(verbose_name='Відповідь (укр)')),
                ('answer_ru', models.TextField(verbose_name='Відповідь (рос)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_uk', models.CharField(default='Прочищення каналізації у Дніпрі', max_length=300, verbose_name='Заголовок (укр)')),
                ('heading_ru', models.CharField(default='Прочистка канализации в Днепре', max_length=300, verbose_name='Заголовок (рос)')),
                ('subheading_uk', models.TextField(default='Професійне прочищення будь-якої складності. Без вихідних, з гарантією результату.', verbose_name='Підзаголовок (укр)')),
                ('subheading_ru', models.TextField(default='Профессиональная прочистка любой сложности. Без выходных, с гарантией результата.', verbose_name='Подзаголовок (рос)')),
                ('cta_primary_uk', models.CharField(default='Розрахувати вартість', max_length=100, verbose_name='Кнопка CTA (укр)')),
                ('cta_primary_ru', models.CharField(default='Рассчитать стоимость', max_length=100, verbose_name='Кнопка CTA (рос)')),
                ('cta_secondary_uk', models.CharField(default='Наші послуги', max_length=100, verbose_name='Кнопка 2 (укр)')),
                ('cta_secondary_ru', models.CharField(default='Наши услуги', max_length=100, verbose_name='Кнопка 2 (рос)')),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фонове зображення')),
            ],
            options={
                'verbose_name': 'Секція Hero',
            },
        ),
        migrations.CreateModel(
            name='HowWeWorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер кроку')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (рос)')),
                ('description_uk', models.TextField(verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(verbose_name='Опис (рос)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Крок «Як ми працюємо»',
                'verbose_name_plural': 'Кроки «Як ми працюємо»',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('text_uk', models.TextField(verbose_name='Відгук (укр)')),
                ('text_ru', models.TextField(verbose_name='Відгук (рос)')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оцінка')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото клієнта')),
                ('service_uk', models.CharField(blank=True, max_length=200, verbose_name='Послуга (укр)')),
                ('service_ru', models.CharField(blank=True, max_length=200, verbose_name='Послуга (рос)')),
                ('created_at', models.DateField(verbose_name='Дата')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Прочищення Каналізації', max_length=200, verbose_name='Назва компанії')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Логотип')),
                ('logo_alt_uk', models.CharField(default='Прочищення каналізації Дніпро', max_length=200, verbose_name='Alt логотипу (укр)')),
                ('logo_alt_ru', models.CharField(default='Прочистка канализации Днепр', max_length=200, verbose_name='Alt логотипу (рос)')),
                ('phone_1', models.CharField(default='+38 (000) 000-00-00', max_length=30, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2')),
                ('phone_1_viber', models.BooleanField(default=True, verbose_name='Viber (тел. 1)')),
                ('phone_1_telegram', models.BooleanField(default=True, verbose_name='Telegram (тел. 1)')),
                ('phone_2_viber', models.BooleanField(default=False, verbose_name='Viber (тел. 2)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_uk', models.CharField(default='м. Дніпро та Дніпропетровська область', max_length=300, verbose_name='Адреса (укр)')),
                ('address_ru', models.CharField(default='г. Днепр и Днепропетровская область', max_length=300, verbose_name='Адреса (рос)')),
                ('working_hours_uk', models.CharField(default='Без вихідних: 06:00–23:00', max_length=100, verbose_name='Години роботи (укр)')),
                ('working_hours_ru', models.CharField(default='Без выходных: 06:00–23:00', max_length=100, verbose_name='Часы работы (рос)')),
                ('footer_text_uk', models.TextField(blank=True, verbose_name='Текст футера (укр)')),
                ('footer_text_ru', models.TextField(blank=True, verbose_name='Текст футера (рос)')),
                ('years_experience', models.PositiveIntegerField(default=5, verbose_name='Років досвіду')),
                ('clients_count', models.CharField(default='1000+', max_length=20, verbose_name='Клієнтів (текст)')),
                ('satisfaction_rate', models.CharField(default='98%', max_length=10, verbose_name='Задоволеність (%)')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(blank=True, help_text='Вставте SVG-код іконки', verbose_name='SVG-іконка')),
                ('title_uk', models.CharField(max_length=200, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (рос)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (рос)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
    ]
