# Generated by Django 6.0.3 on 2026-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('honeypot', models.CharField(blank=True, max_length=100, verbose_name='Не заповнювати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
            ],
            options={
                'verbose_name': 'Повідомлення (контакт)',
                'verbose_name_plural': 'Повідомлення (контакт)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('bathroom', 'Ванна або душ'), ('kitchen', 'Кухня'), ('whole_house', 'Весь будинок / квартира'), ('outdoor', 'На вулиці / зовнішня труба')], max_length=20, verbose_name='Місце засмічення')),
                ('duration', models.CharField(blank=True, choices=[('today', 'Сьогодні'), ('few_days', 'Кілька днів тому'), ('long', 'Кілька тижнів або більше')], max_length=20, verbose_name='Як давно')),
                ('smell', models.CharField(blank=True, choices=[('strong', 'Так, дуже сильний'), ('sometimes', 'Іноді'), ('when_using', 'Тільки під час використання'), ('no', 'Немає')], max_length=20, verbose_name='Запах')),
                ('messenger', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('call', 'Дзвінок')], max_length=20, verbose_name='Месенджер')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('honeypot', models.CharField(blank=True, max_length=100, verbose_name='Не заповнювати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
            ],
            options={
                'verbose_name': 'Заявка (квіз)',
                'verbose_name_plural': 'Заявки (квіз)',
                'ordering': ['-created_at'],
            },
        ),
    ]
