# Generated by Django 6.0.3 on 2026-03-19 16:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.SlugField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('services', 'Послуги'), ('prices', 'Ціни'), ('contact', 'Контакти')], unique=True, verbose_name='Ключ сторінки')),
                ('meta_title_uk', models.CharField(max_length=70, verbose_name='Meta title (укр)')),
                ('meta_title_ru', models.CharField(max_length=70, verbose_name='Meta title (рос)')),
                ('meta_desc_uk', models.CharField(max_length=160, verbose_name='Meta description (укр)')),
                ('meta_desc_ru', models.CharField(max_length=160, verbose_name='Meta description (рос)')),
                ('og_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='OG-зображення')),
                ('schema_json', models.TextField(blank=True, help_text='Додаткова структурована розмітка (JSON-LD) для цієї сторінки', verbose_name='JSON-LD схема')),
            ],
            options={
                'verbose_name': 'SEO сторінки',
                'verbose_name_plural': 'SEO сторінок',
            },
        ),
    ]
